name: Dart

on: [push]
jobs:
  build:
    name: Check flutter lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run linter
        run: dart analyze .
