name: PR checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    
jobs:
  build:
    name: Check PR title
    runs-on: 'ubuntu-latest'
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: 'feat/,fix/,hotfix/'
          prefix_case_sensitive: true
